# Generated by Django 3.1 on 2020-09-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0002_project_task_userprojects'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprojects',
            name='manager',
            field=models.BooleanField(default=False),
        ),
    ]
