# Generated by Django 3.1 on 2020-10-12 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0004_auto_20201008_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprojects',
            name='activated',
            field=models.BooleanField(default=True),
        ),
    ]
