# Generated by Django 3.1 on 2020-10-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0005_userprojects_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='surname',
            field=models.CharField(default='', max_length=128),
        ),
    ]
